#!/usr/bin/env bash
# Display information about subdomains.

get_record_info() {
    local domain=$1
    local subdomain=$2

    record_type=$(dig +short -t A $subdomain.$domain)
    destination=$(dig +short -t A $subdomain.$domain)

    echo "The subdomain $subdomain is a A record and points to $destination"
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            get_record_info $domain $sub
        done
    else
        get_record_info $domain $subdomain
    fi
}

main "$@"
