#!/usr/bin/env bash
# Transfer a file to your server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
ip="$2"
username="$3"
ssh_key="$4"

export SSHPASS="yes"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip:~/"
exit 0
