#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html and move it to the web root
echo "Hello World!" > index.html
sudo mv index.html /var/www/html/

# Create 404.html and move it to the web root
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html/

# Create a new Nginx configuration file in /etc/nginx/sites-available/
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart
