#!/usr/bin/env bash
# Configure Nginx for a custom 404 page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page (you can skip this if not needed)
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Creating the Nginx configuration for the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 page configuration
    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /var/www/html;
    }

    # Other server configurations can be added here if needed
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Removing the default symbolic link (if it exists)
sudo rm -f /etc/nginx/sites-enabled/default

# Creating a symbolic link to enable the site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Testing configurations for syntax errors
sudo nginx -t

# Restarting Nginx after implementing changes
sudo service nginx restart
