#!/usr/bin/env bash
# Configuring Nginx with a custom 404 page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Creating a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configuring Nginx with a custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://github.com/besthor;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Removing the existing symbolic link
sudo rm /etc/nginx/sites-enabled/default

# Creating a new symbolic link to enable the site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Testing configurations for syntax errors
sudo nginx -t

# Restarting Nginx after implementing changes
sudo service nginx restart
