#!/usr/bin/env bash
# install haproxy and enable it on two web servers

sudo apt-get update
sudo apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 1723-web-01 3.84.255.36:80 check
        server 1723-web-02 100.25.3.157:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
