#!/usr/bin/env bash
#displays numbers from 1 to 20
i=1
while [ $i -lt 21 ]
do
	echo "$i"
	case $i in 4)
		echo "bad luck from China"
		;;
	esac
	case $i in 9)
                echo "bad luck from Japan"
                ;;
        esac
	case $i in 17)
                echo "bad luck from Italy"
                ;;
        esac
	(( i++ ))
done
