#!/usr/bin/env bash
# configures a ufw to block all traffic execpt ports 22, 443, 80

sudo apt-get update
sudo apt-get install ufw

sudo ufw default allow outgoing

sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
